export const dashboardData = [
    {
      id: 1,
      title: "Enroll Students",
      count: 0,
      color: "#00BCD4",
      route: "/students/enroll",
    },
    {
      id: 2,
      title: "Assign Students",
      count: 36,
      color: "#607D8B",
      route: "/students/assign",
    },
    {
      id: 3,
      title: "Payment Status",
      count: 59,
      color: "#F44336",
      route: "/payments/status",
    },
    {
      id: 4,
      title: "Paypal Payment",
      count: "$5817.85",
      color: "#4CAF50",
      route: "/payments/paypal",
    },
    {
      id: 5,
      title: "Student Signup",
      count: 74,
      color: "#9E9E9E",
      route: "/students/signup",
    },
    {
      id: 6,
      title: "Teacher Signup",
      count: 25,
      color: "#2196F3",
      route: "/teachers/signup",
    },
    {
      id: 7,
      title: "New Trials",
      count: 4,
      color: "#F44336",
      route: "/trials/new",
    },
    {
      id: 8,
      title: "Assign Trials",
      count: 1,
      color: "#2196F3",
      route: "/trials/assign",
    },
    {
      id: 9,
      title: "Career Requests",
      count: 1,
      color: "#4CAF50",
      route: "/career/requests",
    },
    {
      id: 10,
      title: "Promote Students",
      count: 1,
      color: "#4CAF50",
      route: "/students/promote",
    },
    {
      id: 11,
      title: "Refer a Friend",
      count: 5,
      color: "#9E9E9E",
      route: "/referral",
    },
    {
      id: 12,
      title: "Send Receipt",
      count: 11,
      color: "#4CAF50",
      route: "/payments/send-receipt",
    },
    {
      id: 13,
      title: "Student Leave Form",
      count: 11,
      color: "#F44336",
      route: "/students/leave-form",
    },
    {
      id: 14,
      title: "Student Feedback Form",
      count: 1,
      color: "#2196F3",
      route: "/students/feedback",
    },
  ];
  